import 'dart:ffi' show DynamicLibrary;
import 'dart:io';
import 'generated_bindings.dart';

/// Singleton for managing LMDB native library access
class LMDBNative {
  static LMDBNative? _instance;
  late final LMDBBindings lib;

  // Private constructor
  LMDBNative._() {
    lib = LMDBBindings(_openLibrary());
  }

  // Singleton-acces via lazy initialization
  static LMDBNative get instance {
    return _instance ??= LMDBNative._();
  }

  bool _isStaticallyLinked() {
    try {
      final processLib = DynamicLibrary.process();
      processLib.lookup('mdb_env_create');
      // throws exception if the symbol is unknown
      return true;
    } catch (e) {
      return false;
    }
  }

  /// Asset ID matching the `assetName` registered by the native build hook
  /// in hook/build.dart. The Dart VM resolves this to the actual compiled
  /// library path at runtime via the native assets mapping.
  static const _nativeAssetId = 'package:dart_lmdb/src/generated_bindings.dart';

  DynamicLibrary _openLibrary() {
    if (Platform.isIOS) {
      // for iOS the library is statically linked
      return DynamicLibrary.process();
    }

    if (Platform.isMacOS && _isStaticallyLinked()) {
      // for MacOS the library might be statically linked, if used as Flutter
      // plugin, but for normal Dart usage, it's still a dynamic lib
      return DynamicLibrary.process();
    }

    // Try loading via the native asset ID first. The Dart VM resolves this
    // through the native_assets.yaml mapping generated by the build hook.
    try {
      return DynamicLibrary.open(_nativeAssetId);
    } catch (_) {
      // Fallback: resolve the DLL path from the native_assets.yaml
      // generated by the hooks runner (used by `dart run`).
      final path = _resolveFromNativeAssetsYaml();
      if (path != null) {
        return DynamicLibrary.open(path);
      }
      // Last resort: try the bare library name (works if on system PATH
      // or in the current working directory).
      final libName = Platform.isWindows
          ? 'dart_lmdb.dll'
          : Platform.isMacOS
          ? 'libdart_lmdb.dylib'
          : 'libdart_lmdb.so';
      return DynamicLibrary.open(libName);
    }
  }

  /// Parses `.dart_tool/native_assets.yaml` to find the absolute path of
  /// the compiled LMDB native library.
  ///
  /// Returns `null` if the file doesn't exist or the asset isn't found.
  String? _resolveFromNativeAssetsYaml() {
    // Walk up from the current working directory looking for .dart_tool/
    var dir = Directory.current;
    for (var i = 0; i < 10; i++) {
      final yamlFile = File(
        '${dir.path}${Platform.pathSeparator}.dart_tool${Platform.pathSeparator}native_assets.yaml',
      );
      if (yamlFile.existsSync()) {
        return _parseNativeAssetsYaml(yamlFile);
      }
      final parent = dir.parent;
      if (parent.path == dir.path) break; // reached root
      dir = parent;
    }
    return null;
  }

  /// Very lightweight parser that extracts the DLL path for our asset from
  /// the native_assets.yaml without pulling in a YAML dependency.
  ///
  /// The file format we're looking for:
  /// ```
  /// "package:dart_lmdb/src/generated_bindings.dart": [
  ///   "absolute",
  ///   "F:\\...\\dart_lmdb.dll"
  /// ]
  /// ```
  String? _parseNativeAssetsYaml(File file) {
    try {
      final content = file.readAsStringSync();
      // Find our asset ID in the file
      final assetIdx = content.indexOf(_nativeAssetId);
      if (assetIdx == -1) return null;

      // Find the path value: it's the second element in the JSON array,
      // i.e. the string after "absolute".
      // Look for the pattern: "absolute",\n  "PATH"
      final afterAsset = content.substring(assetIdx);
      final absoluteIdx = afterAsset.indexOf('"absolute"');
      if (absoluteIdx == -1) return null;

      final afterAbsolute = afterAsset.substring(
        absoluteIdx + '"absolute"'.length,
      );
      // Find the next quoted string
      final firstQuote = afterAbsolute.indexOf('"');
      if (firstQuote == -1) return null;
      final secondQuote = afterAbsolute.indexOf('"', firstQuote + 1);
      if (secondQuote == -1) return null;

      final rawPath = afterAbsolute.substring(firstQuote + 1, secondQuote);
      // Unescape JSON-style backslashes
      return rawPath.replaceAll(r'\\', r'\');
    } catch (_) {
      return null;
    }
  }
}
