// Force-included header for Windows DLL symbol exports.
// Uses MSVC linker pragmas to export all public LMDB API symbols.
#ifdef _WIN32

#pragma comment(linker, "/EXPORT:mdb_version")
#pragma comment(linker, "/EXPORT:mdb_strerror")
#pragma comment(linker, "/EXPORT:mdb_env_create")
#pragma comment(linker, "/EXPORT:mdb_env_open")
#pragma comment(linker, "/EXPORT:mdb_env_copy")
#pragma comment(linker, "/EXPORT:mdb_env_copyfd")
#pragma comment(linker, "/EXPORT:mdb_env_copy2")
#pragma comment(linker, "/EXPORT:mdb_env_copyfd2")
#pragma comment(linker, "/EXPORT:mdb_env_stat")
#pragma comment(linker, "/EXPORT:mdb_env_info")
#pragma comment(linker, "/EXPORT:mdb_env_sync")
#pragma comment(linker, "/EXPORT:mdb_env_close")
#pragma comment(linker, "/EXPORT:mdb_env_set_flags")
#pragma comment(linker, "/EXPORT:mdb_env_get_flags")
#pragma comment(linker, "/EXPORT:mdb_env_get_path")
#pragma comment(linker, "/EXPORT:mdb_env_get_fd")
#pragma comment(linker, "/EXPORT:mdb_env_set_mapsize")
#pragma comment(linker, "/EXPORT:mdb_env_set_maxreaders")
#pragma comment(linker, "/EXPORT:mdb_env_get_maxreaders")
#pragma comment(linker, "/EXPORT:mdb_env_set_maxdbs")
#pragma comment(linker, "/EXPORT:mdb_env_get_maxkeysize")
#pragma comment(linker, "/EXPORT:mdb_env_set_userctx")
#pragma comment(linker, "/EXPORT:mdb_env_get_userctx")
#pragma comment(linker, "/EXPORT:mdb_env_set_assert")
#pragma comment(linker, "/EXPORT:mdb_txn_begin")
#pragma comment(linker, "/EXPORT:mdb_txn_env")
#pragma comment(linker, "/EXPORT:mdb_txn_id")
#pragma comment(linker, "/EXPORT:mdb_txn_commit")
#pragma comment(linker, "/EXPORT:mdb_txn_abort")
#pragma comment(linker, "/EXPORT:mdb_txn_reset")
#pragma comment(linker, "/EXPORT:mdb_txn_renew")
#pragma comment(linker, "/EXPORT:mdb_dbi_open")
#pragma comment(linker, "/EXPORT:mdb_stat")
#pragma comment(linker, "/EXPORT:mdb_dbi_flags")
#pragma comment(linker, "/EXPORT:mdb_dbi_close")
#pragma comment(linker, "/EXPORT:mdb_drop")
#pragma comment(linker, "/EXPORT:mdb_set_compare")
#pragma comment(linker, "/EXPORT:mdb_set_dupsort")
#pragma comment(linker, "/EXPORT:mdb_set_relfunc")
#pragma comment(linker, "/EXPORT:mdb_set_relctx")
#pragma comment(linker, "/EXPORT:mdb_get")
#pragma comment(linker, "/EXPORT:mdb_put")
#pragma comment(linker, "/EXPORT:mdb_del")
#pragma comment(linker, "/EXPORT:mdb_cursor_open")
#pragma comment(linker, "/EXPORT:mdb_cursor_close")
#pragma comment(linker, "/EXPORT:mdb_cursor_renew")
#pragma comment(linker, "/EXPORT:mdb_cursor_txn")
#pragma comment(linker, "/EXPORT:mdb_cursor_dbi")
#pragma comment(linker, "/EXPORT:mdb_cursor_get")
#pragma comment(linker, "/EXPORT:mdb_cursor_put")
#pragma comment(linker, "/EXPORT:mdb_cursor_del")
#pragma comment(linker, "/EXPORT:mdb_cursor_count")
#pragma comment(linker, "/EXPORT:mdb_cmp")
#pragma comment(linker, "/EXPORT:mdb_dcmp")
#pragma comment(linker, "/EXPORT:mdb_reader_list")
#pragma comment(linker, "/EXPORT:mdb_reader_check")

#endif
